public static class KnownItemSeedData
{
    // Seed data for the KnownItem table, migrated from the old hardcoded catalog.
    // Kategorierne følger butikkens afdelinger, ikke fødevaretype - derfor ligger f.eks.
    // frugt under Grønt, og fersk kød under Køl, i stedet for at have egne kategorier.
    public static readonly (string Name, string Category)[] Entries =
    {
        // Grønt (grøntsager og frugt)
        ("tomat", "Grønt"),
        ("agurk", "Grønt"),
        ("løg", "Grønt"),
        ("forårsløg", "Grønt"),
        ("kartoffel", "Grønt"),
        ("kartofler", "Grønt"),
        ("gulerod", "Grønt"),
        ("gulerødder", "Grønt"),
        ("peberfrugt", "Grønt"),
        ("broccoli", "Grønt"),
        ("spinat", "Grønt"),
        ("salat", "Grønt"),
        ("icebergsalat", "Grønt"),
        ("rucola", "Grønt"),
        ("hvidløg", "Grønt"),
        ("chili", "Grønt"),
        ("champignon", "Grønt"),
        ("courgette", "Grønt"),
        ("aubergine", "Grønt"),
        ("rødbede", "Grønt"),
        ("persille", "Grønt"),
        ("purløg", "Grønt"),
        ("ingefær", "Grønt"),
        ("blomkål", "Grønt"),
        ("rødkål", "Grønt"),
        ("hvidkål", "Grønt"),
        ("grønkål", "Grønt"),
        ("porre", "Grønt"),
        ("selleri", "Grønt"),
        ("radise", "Grønt"),
        ("majskolbe", "Grønt"),
        ("avocado", "Grønt"),
        ("basilikum", "Grønt"),
        ("dild", "Grønt"),
        ("timian", "Grønt"),
        ("rosmarin", "Grønt"),
        ("mynte", "Grønt"),
        ("æble", "Grønt"),
        ("æbler", "Grønt"),
        ("banan", "Grønt"),
        ("bananer", "Grønt"),
        ("appelsin", "Grønt"),
        ("citron", "Grønt"),
        ("pære", "Grønt"),
        ("vindruer", "Grønt"),
        ("jordbær", "Grønt"),
        ("blåbær", "Grønt"),
        ("hindbær", "Grønt"),
        ("ananas", "Grønt"),
        ("mango", "Grønt"),
        ("kiwi", "Grønt"),
        ("melon", "Grønt"),
        ("vandmelon", "Grønt"),
        ("fersken", "Grønt"),
        ("blomme", "Grønt"),
        ("nektarin", "Grønt"),
        ("mandarin", "Grønt"),
        ("clementin", "Grønt"),
        ("lime", "Grønt"),
        ("granatæble", "Grønt"),
        ("abrikos", "Grønt"),

        // Køl (fersk kød, fisk, æg, pålæg, køledisk-retter)
        ("kylling", "Køl"),
        ("kyllingefilet", "Køl"),
        ("kyllingebryst", "Køl"),
        ("oksekød", "Køl"),
        ("svinekød", "Køl"),
        ("hakkekød", "Køl"),
        ("bacon", "Køl"),
        ("pølser", "Køl"),
        ("skinke", "Køl"),
        ("flæskesteg", "Køl"),
        ("frikadeller", "Køl"),
        ("medister", "Køl"),
        ("spegepølse", "Køl"),
        ("leverpostej", "Køl"),
        ("rullepølse", "Køl"),
        ("pålæg", "Køl"),
        ("salami", "Køl"),
        ("æg", "Køl"),
        ("laks", "Køl"),
        ("torsk", "Køl"),
        ("rejer", "Køl"),
        ("fiskefilet", "Køl"),
        ("lasagne", "Køl"),
        ("tortellini", "Køl"),
        ("hummus", "Køl"),
        ("tofu", "Køl"),
        ("pesto", "Køl"),
        ("guacamole", "Køl"),
        ("tzatziki", "Køl"),
        ("remoulade", "Køl"),

        // Mejeri
        ("mælk", "Mejeri"),
        ("minimælk", "Mejeri"),
        ("letmælk", "Mejeri"),
        ("sødmælk", "Mejeri"),
        ("kærnemælk", "Mejeri"),
        ("fløde", "Mejeri"),
        ("piskefløde", "Mejeri"),
        ("yoghurt", "Mejeri"),
        ("skyr", "Mejeri"),
        ("ost", "Mejeri"),
        ("smør", "Mejeri"),
        ("creme fraiche", "Mejeri"),
        ("cottage cheese", "Mejeri"),
        ("mascarpone", "Mejeri"),
        ("parmesan", "Mejeri"),
        ("feta", "Mejeri"),
        ("cheddar", "Mejeri"),
        ("mozzarella", "Mejeri"),
        ("kvark", "Mejeri"),
        ("rygeost", "Mejeri"),
        ("chokolademælk", "Mejeri"),
        ("margarine", "Mejeri"),

        // Konserve
        ("flåede tomater", "Konserve"),
        ("majs", "Konserve"),
        ("bønner", "Konserve"),
        ("tun", "Konserve"),
        ("ærter", "Konserve"),
        ("linser", "Konserve"),
        ("sild", "Konserve"),
        ("makrel i tomat", "Konserve"),
        ("agurkesalat", "Konserve"),
        ("rødbeder", "Konserve"),
        ("kikærter", "Konserve"),
        ("tomatpuré", "Konserve"),
        ("oliven", "Konserve"),
        ("sylteagurker", "Konserve"),
        ("asier", "Konserve"),
        ("kokosmælk", "Konserve"),

        // Brød
        ("brød", "Brød"),
        ("rugbrød", "Brød"),
        ("franskbrød", "Brød"),
        ("boller", "Brød"),
        ("rundstykker", "Brød"),
        ("toastbrød", "Brød"),
        ("knækbrød", "Brød"),
        ("pitabrød", "Brød"),
        ("tortilla", "Brød"),
        ("croissant", "Brød"),
        ("bagel", "Brød"),
        ("flütes", "Brød"),
        ("grovbrød", "Brød"),
        ("surdejsbrød", "Brød"),
        ("naanbrød", "Brød"),

        // Tørvarer
        ("ris", "Tørvarer"),
        ("pasta", "Tørvarer"),
        ("mel", "Tørvarer"),
        ("hvedemel", "Tørvarer"),
        ("speltmel", "Tørvarer"),
        ("sukker", "Tørvarer"),
        ("flormelis", "Tørvarer"),
        ("salt", "Tørvarer"),
        ("peber", "Tørvarer"),
        ("paprika", "Tørvarer"),
        ("karry", "Tørvarer"),
        ("kanel", "Tørvarer"),
        ("havregryn", "Tørvarer"),
        ("müsli", "Tørvarer"),
        ("cornflakes", "Tørvarer"),
        ("nødder", "Tørvarer"),
        ("mandler", "Tørvarer"),
        ("rosiner", "Tørvarer"),
        ("bouillon", "Tørvarer"),
        ("olie", "Tørvarer"),
        ("olivenolie", "Tørvarer"),
        ("eddike", "Tørvarer"),
        ("honning", "Tørvarer"),
        ("peanutbutter", "Tørvarer"),
        ("nutella", "Tørvarer"),
        ("couscous", "Tørvarer"),
        ("quinoa", "Tørvarer"),
        ("bulgur", "Tørvarer"),
        ("chiafrø", "Tørvarer"),

        // Drikkevarer
        ("øl", "Drikkevarer"),
        ("vin", "Drikkevarer"),
        ("sodavand", "Drikkevarer"),
        ("cola", "Drikkevarer"),
        ("juice", "Drikkevarer"),
        ("saft", "Drikkevarer"),
        ("most", "Drikkevarer"),
        ("kaffe", "Drikkevarer"),
        ("te", "Drikkevarer"),
        ("kakao", "Drikkevarer"),
        ("vand", "Drikkevarer"),
        ("danskvand", "Drikkevarer"),
        ("energidrik", "Drikkevarer"),

        // Slik
        ("chokolade", "Slik"),
        ("bolsjer", "Slik"),
        ("vingummi", "Slik"),
        ("lakrids", "Slik"),
        ("chips", "Slik"),
        ("popcorn", "Slik"),
        ("kiks", "Slik"),
        ("småkager", "Slik"),
        ("skumfiduser", "Slik"),
        ("marshmallows", "Slik"),

        // Frost
        ("is", "Frost"),
        ("pommes frites", "Frost"),
        ("frosne grøntsager", "Frost"),
        ("frosne bær", "Frost"),
        ("pizza", "Frost"),
        ("frosne fiskefileter", "Frost"),
        ("frosne boller", "Frost"),
        ("frosne rejer", "Frost"),
        ("frossen spinat", "Frost"),
        ("isterninger", "Frost"),

        // Rengøring
        ("opvaskemiddel", "Rengøring"),
        ("toiletpapir", "Rengøring"),
        ("rengøringsmiddel", "Rengøring"),
        ("vaskepulver", "Rengøring"),
        ("svamp", "Rengøring"),
        ("affaldsposer", "Rengøring"),
        ("køkkenrulle", "Rengøring"),
        ("skyllemiddel", "Rengøring"),
        ("allrengøring", "Rengøring"),
        ("klorin", "Rengøring"),
        ("vinduespudser", "Rengøring"),
        ("håndsæbe", "Rengøring"),
        ("opvaskebørste", "Rengøring"),
    };
}
